#!/bin/bash


#////////////////////////////////////////////////////////////////////////////
#//
#//   High-pass filtering (for spikes)
#//
#//   copyright       (C) 2007-2010 by Michaël Zugaro
#//   email           michael.zugaro@college-de-france.fr
#//
#//   This program is free software; you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation; either version 3 of the License, or
#//   (at your option) any later version.
#//
#////////////////////////////////////////////////////////////////////////////

# Source helper functions
source ndm_functions

# Parse command-line
program=$(basename $0)
if [ $# -ne 1 ]
then
	echo_error "usage: $program xml-file"
	exit $GENERAL_ERROR
fi
session=${1%.xml}
directory=$(basename "$(pwd)")

# Print a header to indicate current processing step
print_header "$session - High-pass filtering"

# Check input and output files
outputs_exist $session.fil && exit $OUTPUTS_EXIST
inputs_missing $session.xml $session.dat && exit $INPUTS_MISSING

# Check required programs
check_commands_installed xpathReader process_medianfilter

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Read Parameters
# ////////////////////////////////////////////////////////////////////////////////////////////////

nChannels=$(xml_read $session "//acquisitionSystem/nChannels")
windowHalfLength=$(read_script_parameter $session windowHalfLength)
# chunkSize: bytes to process per pass (default 64 GiB).
# Can be overridden per-session in the XML <ndm_hipass> parameters block.
# Uses xml_read directly with the correct <n> element XPath (not read_script_parameter
# which incorrectly searches for <name> elements).
chunkSize=$(xml_read $session "//program/n[.='ndm_hipass']/../parameters/parameter/n[.='chunkSize']/../value")
chunkSize=${chunkSize:-68719476736}   # default: 64 GiB = 64*1024*1024*1024

check_mandatory_variable $nChannels "missing number of channels"
check_mandatory_variable $windowHalfLength "missing window half-length"

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Process
# ////////////////////////////////////////////////////////////////////////////////////////////////

process_medianfilter -n $nChannels -w $windowHalfLength -b $chunkSize -v $session.dat $session.fil
check_command_status process_medianfilter
